In [1]:
import torch

In [2]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
x.requires_grad_(True) # 将梯度存于x中
x.grad

In [7]:
y = 2 * torch.dot(x,x);
y

tensor(28., grad_fn=<MulBackward0>)

In [8]:
y.backward() # 反向累计
x.grad

tensor([ 0.,  8., 16., 24.])

In [9]:
x.grad.zero_() # pytorch会积累梯度，计算前梯度清0
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [10]:
x.grad.zero_()
y = x * x # 哈达玛积 y为矩阵 一般不用矩阵进行求导
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [11]:
x.grad.zero_()
y = x * x
u = y.detach() # 将y看做常数
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])