In [93]:
import torch

In [94]:
A = torch.arange(12,dtype=torch.float32).reshape(3,4)

In [95]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [96]:
B = A.clone()

In [97]:
A.shape,A.shape[0],A.numel()

(torch.Size([3, 4]), 3, 12)

In [98]:
A.mean(),A.sum(),A * B , A.sum() / A.numel()

(tensor(5.5000),
 tensor(66.),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.]]),
 tensor(5.5000))

In [119]:
A.mean(axis=0),A.sum(axis=0),A * B # 如果keepdim=True axis=0 求和后变成(1,4) axis=1 求和后变成(3,1),

(tensor([4., 5., 6., 7.]),
 tensor([12., 15., 18., 21.]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.]]))

In [121]:
A.sum(axis=0)

tensor([12., 15., 18., 21.])

In [54]:
A.shape[0]

3

In [55]:
A.shape[1]

4

In [52]:
A.sum(axis=0) / A.shape[0] # 和每一列求均值一样

tensor([4., 5., 6., 7.])

In [44]:
sum_A = A.sum(axis=1,keepdim=True) # 保留维度信息
sum_A

tensor([[ 6.],
        [22.],
        [38.]])

In [45]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895]])

In [50]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.]])

In [72]:
# 点积是相同位置元素乘积的和
y = torch.ones(4,dtype=torch.float32)
x = torch.arange(4,dtype=torch.float32)
x,y

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]))

In [63]:
torch.dot(x,y)

tensor(6.)

In [64]:
torch.sum(x*y)

tensor(6.)

In [74]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A,A.shape,x.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 torch.Size([4]))

In [75]:
torch.mv(A,x)
# (m,n)(n,1) = (m,1)
# 注意在mv方法里，第二个参数必须是一个一维向量，也就是说repshae(4,1)是不行的，这实际上是一个二维向量

tensor([ 14.,  38.,  62.,  86., 110.])

In [76]:
# 矩阵乘法
B = torch.ones(4,3,dtype=torch.float32)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [77]:
# L2范数是向量元素平方和的平方根
u = torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

In [78]:
# L1范数是向量元素的绝对值之和
torch.abs(u).sum()

tensor(7.)

In [80]:
# 矩阵的F范数是矩阵元素的平方和的平方根
torch.norm(torch.ones((4,9)))

tensor(6.)

In [110]:
# axis用法
# 第一个嵌套列表有2个列表，2个元素内每个元素内嵌套5个列表，再在里面每个有4个元素
a = torch.ones((2,5,4))
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [116]:
a.sum(axis=0,keepdim=True)
# 实际上是把原来的对应维度的对应项求和再将相应维度下元素个数变为1(消除对应维度)

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])

In [122]:
a.sum(axis=[0,2],keepdim=True)

tensor([[[8.],
         [8.],
         [8.],
         [8.],
         [8.]]])